<!--<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:sch="http://transaction.services" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://transaction.services" targetNamespace="http://transaction.services">-->
<!--    <wsdl:types>-->
<!--        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">-->
<!--            <xsd:import namespace="http://transaction.services" schemaLocation="transaction.xsd"/>-->
<!--        </xsd:schema>-->
<!--    </wsdl:types>-->
<!--    <wsdl:message name="filterByReceiverRequest">-->
<!--        <wsdl:part element="tns:filterByReceiverRequest" name="filterByReceiverRequest"> </wsdl:part>-->
<!--    </wsdl:message>-->
<!--    <wsdl:message name="filterByAmountResponse">-->
<!--        <wsdl:part element="tns:filterByAmountResponse" name="filterByAmountResponse"> </wsdl:part>-->
<!--    </wsdl:message>-->
<!--    <wsdl:message name="newTransactionRequest">-->
<!--        <wsdl:part element="tns:newTransactionRequest" name="newTransactionRequest"> </wsdl:part>-->
<!--    </wsdl:message>-->
<!--    <wsdl:message name="updateTransactionResponse">-->
<!--        <wsdl:part element="tns:updateTransactionResponse" name="updateTransactionResponse"> </wsdl:part>-->
<!--    </wsdl:message>-->
<!--    <wsdl:message name="filterByReceiverResponse">-->
<!--        <wsdl:part element="tns:filterByReceiverResponse" name="filterByReceiverResponse"> </wsdl:part>-->
<!--    </wsdl:message>-->
<!--    <wsdl:message name="updateTransactionRequest">-->
<!--        <wsdl:part element="tns:updateTransactionRequest" name="updateTransactionRequest"> </wsdl:part>-->
<!--    </wsdl:message>-->
<!--    <wsdl:message name="filterByAmountRequest">-->
<!--        <wsdl:part element="tns:filterByAmountRequest" name="filterByAmountRequest"> </wsdl:part>-->
<!--    </wsdl:message>-->
<!--    <wsdl:message name="closeTransactionRequest">-->
<!--        <wsdl:part element="tns:closeTransactionRequest" name="closeTransactionRequest"> </wsdl:part>-->
<!--    </wsdl:message>-->
<!--    <wsdl:message name="filterBySenderResponse">-->
<!--        <wsdl:part element="tns:filterBySenderResponse" name="filterBySenderResponse"> </wsdl:part>-->
<!--    </wsdl:message>-->
<!--    <wsdl:message name="newTransactionResponse">-->
<!--        <wsdl:part element="tns:newTransactionResponse" name="newTransactionResponse"> </wsdl:part>-->
<!--    </wsdl:message>-->
<!--    <wsdl:message name="closeTransactionResponse">-->
<!--        <wsdl:part element="tns:closeTransactionResponse" name="closeTransactionResponse"> </wsdl:part>-->
<!--    </wsdl:message>-->
<!--    <wsdl:message name="filterBySenderRequest">-->
<!--        <wsdl:part element="tns:filterBySenderRequest" name="filterBySenderRequest"> </wsdl:part>-->
<!--    </wsdl:message>-->
<!--    <wsdl:portType name="TransactionPort">-->
<!--        <wsdl:operation name="filterByReceiver">-->
<!--            <wsdl:input message="tns:filterByReceiverRequest" name="filterByReceiverRequest"> </wsdl:input>-->
<!--            <wsdl:output message="tns:filterByReceiverResponse" name="filterByReceiverResponse"> </wsdl:output>-->
<!--        </wsdl:operation>-->
<!--        <wsdl:operation name="filterByAmount">-->
<!--            <wsdl:input message="tns:filterByAmountRequest" name="filterByAmountRequest"> </wsdl:input>-->
<!--            <wsdl:output message="tns:filterByAmountResponse" name="filterByAmountResponse"> </wsdl:output>-->
<!--        </wsdl:operation>-->
<!--        <wsdl:operation name="newTransaction">-->
<!--            <wsdl:input message="tns:newTransactionRequest" name="newTransactionRequest"> </wsdl:input>-->
<!--            <wsdl:output message="tns:newTransactionResponse" name="newTransactionResponse"> </wsdl:output>-->
<!--        </wsdl:operation>-->
<!--        <wsdl:operation name="updateTransaction">-->
<!--            <wsdl:input message="tns:updateTransactionRequest" name="updateTransactionRequest"> </wsdl:input>-->
<!--            <wsdl:output message="tns:updateTransactionResponse" name="updateTransactionResponse"> </wsdl:output>-->
<!--        </wsdl:operation>-->
<!--        <wsdl:operation name="closeTransaction">-->
<!--            <wsdl:input message="tns:closeTransactionRequest" name="closeTransactionRequest"> </wsdl:input>-->
<!--            <wsdl:output message="tns:closeTransactionResponse" name="closeTransactionResponse"> </wsdl:output>-->
<!--        </wsdl:operation>-->
<!--        <wsdl:operation name="filterBySender">-->
<!--            <wsdl:input message="tns:filterBySenderRequest" name="filterBySenderRequest"> </wsdl:input>-->
<!--            <wsdl:output message="tns:filterBySenderResponse" name="filterBySenderResponse"> </wsdl:output>-->
<!--        </wsdl:operation>-->
<!--    </wsdl:portType>-->
<!--    <wsdl:binding name="TransactionPortSoap11" type="tns:TransactionPort">-->
<!--        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>-->
<!--        <wsdl:operation name="filterByReceiver">-->
<!--            <soap:operation soapAction=""/>-->
<!--            <wsdl:input name="filterByReceiverRequest">-->
<!--                <soap:body use="literal"/>-->
<!--            </wsdl:input>-->
<!--            <wsdl:output name="filterByReceiverResponse">-->
<!--                <soap:body use="literal"/>-->
<!--            </wsdl:output>-->
<!--        </wsdl:operation>-->
<!--        <wsdl:operation name="filterByAmount">-->
<!--            <soap:operation soapAction=""/>-->
<!--            <wsdl:input name="filterByAmountRequest">-->
<!--                <soap:body use="literal"/>-->
<!--            </wsdl:input>-->
<!--            <wsdl:output name="filterByAmountResponse">-->
<!--                <soap:body use="literal"/>-->
<!--            </wsdl:output>-->
<!--        </wsdl:operation>-->
<!--        <wsdl:operation name="newTransaction">-->
<!--            <soap:operation soapAction=""/>-->
<!--            <wsdl:input name="newTransactionRequest">-->
<!--                <soap:body use="literal"/>-->
<!--            </wsdl:input>-->
<!--            <wsdl:output name="newTransactionResponse">-->
<!--                <soap:body use="literal"/>-->
<!--            </wsdl:output>-->
<!--        </wsdl:operation>-->
<!--        <wsdl:operation name="updateTransaction">-->
<!--            <soap:operation soapAction=""/>-->
<!--            <wsdl:input name="updateTransactionRequest">-->
<!--                <soap:body use="literal"/>-->
<!--            </wsdl:input>-->
<!--            <wsdl:output name="updateTransactionResponse">-->
<!--                <soap:body use="literal"/>-->
<!--            </wsdl:output>-->
<!--        </wsdl:operation>-->
<!--        <wsdl:operation name="closeTransaction">-->
<!--            <soap:operation soapAction=""/>-->
<!--            <wsdl:input name="closeTransactionRequest">-->
<!--                <soap:body use="literal"/>-->
<!--            </wsdl:input>-->
<!--            <wsdl:output name="closeTransactionResponse">-->
<!--                <soap:body use="literal"/>-->
<!--            </wsdl:output>-->
<!--        </wsdl:operation>-->
<!--        <wsdl:operation name="filterBySender">-->
<!--            <soap:operation soapAction=""/>-->
<!--            <wsdl:input name="filterBySenderRequest">-->
<!--                <soap:body use="literal"/>-->
<!--            </wsdl:input>-->
<!--            <wsdl:output name="filterBySenderResponse">-->
<!--                <soap:body use="literal"/>-->
<!--            </wsdl:output>-->
<!--        </wsdl:operation>-->
<!--    </wsdl:binding>-->
<!--    <wsdl:service name="TransactionPortService">-->
<!--        <wsdl:port binding="tns:TransactionPortSoap11" name="TransactionPortSoap11">-->
<!--            <soap:address location="http://localhost:8082/transactionrepo"/>-->
<!--        </wsdl:port>-->
<!--    </wsdl:service>-->
<!--</wsdl:definitions>-->